# Generated by Django 6.0.3 on 2026-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Soutenance', 'Soutenance'), ('TP/Atelier', 'TP / Atelier'), ('Conférence', 'Conférence'), ('Fête', 'Fête scolaire'), ('Autre', 'Autre')], default='Autre', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
