def translations(request):
    lang = getattr(request, 'LANGUAGE_CODE', 'fr')
    
    # Dictionnaire de traductions pour les éléments de l'interface
    translations_dict = {
        'fr': {
            'menu_principal': 'Menu Principal',
            'dashboard_label': 'Tableau de bord',
            'administration': 'Administration',
            'txt_students': 'Étudiants',
            'txt_teachers': 'Enseignants',
            'txt_departments': 'Départements',
            'txt_subjects': 'Matières',
            'academic_management': 'Gestion Académique',
            'settings': 'Paramètres',
            'logout': 'Déconnexion',
            'welcome_to': 'Bienvenue sur',
            'dashboard_subtitle': 'Tableau de bord de gestion scolaire intelligent et moderne.',
            'gender_distribution': 'Répartition par Genre',
            'teacher_distribution': 'Répartition des Enseignants',
            'boys': 'Garçons',
            'girls': 'Filles',
            'list_students': 'Liste des étudiants',
            'add_student': 'Ajouter un étudiant',
            'list_teachers': 'Liste des enseignants',
            'add_teacher': 'Ajouter un enseignant',
            'list_departments': 'Liste des départements',
            'add_department': 'Ajouter un département',
            'list_subjects': 'Liste des matières',
            'add_subject': 'Ajouter une matière',
            'txt_exams': 'Examens',
            'txt_holidays': 'Vacances',
            'txt_fees': 'Frais',
            'txt_events': 'Évènements',
            'txt_timetable': 'Emploi du temps',
            'txt_library': 'Bibliothèque',
            'teacher_space': 'Espace Enseignant',
            'my_classes': 'Mes Classes',
            'enter_grades': 'Saisir les Notes',
            'txt_attendance': 'Présences',
            'student_space': 'Espace Étudiant',
            'my_courses': 'Mes Cours',
            'my_exams': 'Mes Examens',
            'sys_admin': 'Administrateur Système',
            'teacher': 'Enseignant',
            'student': 'Étudiant',
            'total_students': 'Total Étudiants',
            'present_today': 'Présents aujourd\'hui',
            'absent_today': 'Absents aujourd\'hui',
            'latest_grades': 'Dernières Notes',
            'class_filter': 'Filtrer par Classe',
            'date_filter': 'Filtrer par Date',
            'welcome_back': 'Ravi de vous revoir',
            'dashboard_desc': 'Explorez vos outils de gestion de campus. Gérez les absences, les notes et les emplois du temps en quelques clics.',
        },
        'en': {
            'menu_principal': 'Main Menu',
            'dashboard_label': 'Dashboard',
            'administration': 'Administration',
            'txt_students': 'Students',
            'txt_teachers': 'Teachers',
            'txt_departments': 'Departments',
            'txt_subjects': 'Subjects',
            'academic_management': 'Academic Management',
            'settings': 'Settings',
            'logout': 'Logout',
            'welcome_to': 'Welcome to',
            'dashboard_subtitle': 'Modern and smart school management dashboard.',
            'gender_distribution': 'Gender Distribution',
            'teacher_distribution': 'Teachers Distribution',
            'boys': 'Boys',
            'girls': 'Girls',
            'list_students': 'Students List',
            'add_student': 'Add Student',
            'list_teachers': 'Teachers List',
            'add_teacher': 'Add Teacher',
            'list_departments': 'Departments List',
            'add_department': 'Add Department',
            'list_subjects': 'Subjects List',
            'add_subject': 'Add Subject',
            'txt_exams': 'Exams',
            'txt_holidays': 'Holidays',
            'txt_fees': 'Fees',
            'txt_events': 'Events',
            'txt_timetable': 'Timetable',
            'txt_library': 'Library',
            'teacher_space': 'Teacher Space',
            'my_classes': 'My Classes',
            'enter_grades': 'Enter Grades',
            'txt_attendance': 'Attendance',
            'student_space': 'Student Space',
            'my_courses': 'My Courses',
            'my_exams': 'My Exams',
            'sys_admin': 'System Administrator',
            'teacher': 'Teacher',
            'student': 'Student',
            'total_students': 'Total Students',
            'present_today': 'Present Today',
            'absent_today': 'Absent Today',
            'latest_grades': 'Latest Grades',
            'class_filter': 'Filter by Class',
            'date_filter': 'Filter by Date',
            'welcome_back': 'Welcome back',
            'dashboard_desc': 'Explore your campus management tools. Manage absences, grades and timetables with a few clicks.',
        },
        'ar': {
            'menu_principal': 'القائمة الرئيسية',
            'dashboard_label': 'لوحة التحكم',
            'administration': 'الإدارة',
            'txt_students': 'الطلاب',
            'txt_teachers': 'المعلمون',
            'txt_departments': 'الأقسام',
            'txt_subjects': 'المواد',
            'academic_management': 'الإدارة الأكاديمية',
            'settings': 'الإعدادات',
            'logout': 'تسجيل الخروج',
            'welcome_to': 'مرحباً بك في',
            'dashboard_subtitle': 'لوحة تحكم ذكية وحديثة لإدارة المدرسة.',
            'gender_distribution': 'توزيع الجنس',
            'teacher_distribution': 'توزيع المعلمين',
            'boys': 'أولاد',
            'girls': 'بنات',
            'list_students': 'قائمة الطلاب',
            'add_student': 'إضافة طالب',
            'list_teachers': 'قائمة المعلمين',
            'add_teacher': 'إضافة معلم',
            'list_departments': 'قائمة الأقسام',
            'add_department': 'إضافة قسم',
            'list_subjects': 'قائمة المواد',
            'add_subject': 'إضافة مادة',
            'txt_exams': 'الامتحانات',
            'txt_holidays': 'العطلات',
            'txt_fees': 'الرسوم',
            'txt_events': 'الفعاليات',
            'txt_timetable': 'الجدول الزمني',
            'txt_library': 'المكتبة',
            'teacher_space': 'مساحة المعلم',
            'my_classes': 'فصولي',
            'enter_grades': 'إدخال الدرجات',
            'txt_attendance': 'الحضور',
            'student_space': 'مساحة الطالب',
            'my_courses': 'دوراتي',
            'my_exams': 'امتحاناتي',
            'sys_admin': 'مدير النظام',
            'teacher': 'معلم',
            'student': 'طالب',
            'total_students': 'إجمالي الطلاب',
            'present_today': 'الحاضرون اليوم',
            'absent_today': 'الغائبون اليوم',
            'latest_grades': 'آخر الدرجات',
            'class_filter': 'تصفية حسب الفصل',
            'date_filter': 'تصفية حسب التاريخ',
            'welcome_back': 'مرحباً بعودتك',
            'dashboard_desc': 'استكشف أدوات إدارة الحرم الجامعي الخاص بك. قم بإدارة الغيابات، الدرجات، والجداول الزمنية بنقرات قليلة.',
        }
    }
    
    # On récupère les traductions pour la langue actuelle (fr par défaut)
    return translations_dict.get(lang[:2], translations_dict['fr'])
