# Generated by Django 6.0.3 on 2026-04-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
