# Generated by Django 6.0.3 on 2026-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='coefficient',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
