# Generated by Django 6.0.3 on 2026-04-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_exam_coefficient_exam_duration_alter_exam_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
    ]
