# Generated by Django 6.0.3 on 2026-04-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_question_coursesessionlog_choice_quiz_question_quiz_and_more'),
        ('teachers', '0002_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesessionlog',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='teachers.teacher'),
        ),
    ]
