# Generated by Django 6.0.3 on 2026-04-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_appointment_homeworksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom exact pour la base de données (ex: 'Tronc Commun Sciences 1')", max_length=200)),
                ('level', models.CharField(blank=True, help_text="Niveau général (ex: 'Tronc Commun')", max_length=50, null=True)),
            ],
        ),
    ]
